name: Node CI2

on:
  workflow_call:
    inputs:
      node-version:
        type: string
        default: '20'

jobs:
  node-ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}

      - run: npm install

      - name: Lint
        run: npm run lint

      - name: Security scan
        run: npm audit --audit-level=high

      - name: Tests
        run: npm test
