name: Python CI

on:
  workflow_call:
    inputs:
      python-version:
        type: string
        default: '3.12'

jobs:
  python-ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version }}

      - run: echo "Python CI template - nog leeg"
